# Generated by Django 3.2.18 on 2023-05-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anno', models.DateField()),
                ('Marca', models.CharField(max_length=255)),
                ('Color', models.CharField(max_length=255)),
                ('Combustible', models.CharField(max_length=255)),
                ('NumPuertas', models.IntegerField()),
                ('Traccion', models.CharField(max_length=255)),
            ],
        ),
    ]
